services:
  memcached:
    image: memcached:latest
    container_name: memcached_piler
    restart: unless-stopped
    networks:
      - pilernet
    cap_drop:
      - ALL
    command: -m 64

  piler:
    image: simatec/piler:${PILER_VERSION}
    container_name: piler
    restart: unless-stopped
    networks:
      - pilernet
    hostname: ${PILER_DOMAIN}
    init: true
    environment:
      - MEMCACHED_HOSTNAME=memcached
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - PILER_HOSTNAME=${PILER_DOMAIN}
      - MEMCACHED_HOST=memcached_piler
      - TZ=${TIME_ZONE}
      - RT=1
    ports:
      - "${SMTP_PORT}:25"
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - piler_etc:/etc/piler
      - piler_var_store:/var/piler/store
      - piler_var_manticore:/var/piler/manticore
      - piler_var_imap:/var/piler/imap
      - piler_var_stat:/var/piler/stat
      - piler_cron:/var/spool/cron/crontabs
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: curl -s smtp://localhost/
      interval: "60s"
      timeout: "3s"
      start_period: "15s"
      retries: 3
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 512M
    depends_on:
      - memcached

networks:
  pilernet:
    external: true

volumes:
  piler_etc:
  piler_var_store:
  piler_var_manticore:
  piler_var_imap:
  piler_var_stat:
  piler_cron:
